### ISSUE TITLE
Error retrieving data

### ISSUE THREAD

**Issue by sacredland** [oddluck/limnoria-plugins#19]
Error retrieving data from https://www.worldometers.info/coronavirus/

**Comment by Estella** [comment]
seems to be hit or miss, had an error, but issue is resolved as of now, maybe issues on their end?
```
ERROR 2020-05-15T04:43:31 supybot Uncaught exception in ['corona'].
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supybot/callbacks.py", line 1319, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/supybot/utils/python.py", line 90, in g
    f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/supybot/callbacks.py", line 1285, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/supybot/commands.py", line 1104, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/katie/Limnoria/plugins/Corona/plugin.py", line 642, in corona
    if not self.get_data():
  File "/home/katie/Limnoria/plugins/Corona/plugin.py", line 430, in get_data
    reverse=True,
  File "/home/katie/Limnoria/plugins/Corona/plugin.py", line 428, in <lambda>
    if len(k_v) == len(self.headers["countries"])
ValueError: invalid literal for int() with base 10: ''
ERROR 2020-05-15T04:43:31 supybot Exception id: 0xae96a
```

**Comment by oddluck** [comment]
Thanks for the issue. Sorry to take so long, but fixed in https://github.com/oddluck/limnoria-plugins/commit/39075d38932185d03e9fc55190623a6043ad356d
