### ISSUE TITLE
CBB plugin results in error

### ISSUE THREAD

**Issue by waltflanagan53** [oddluck/limnoria-plugins#49]
Using the CBB plugin causes bot to respond with "An error has occurred and has been logged. Check the logs for more information."

Logs show the following error:
```
ERROR 2022-11-27T17:04:01 Uncaught exception in ['cbb'].
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/supybot/callbacks.py", line 1587, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/supybot/utils/python.py", line 91, in g
    f(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/supybot/callbacks.py", line 1553, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/supybot/commands.py", line 1163, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/config/plugins/CBB/plugin.py", line 108, in cbb
    SCORES = self._checkscores()
  File "/config/plugins/CBB/plugin.py", line 226, in _checkscores
    0 < comp["competitors"][0]["curatedRank"]["current"] <= 25
KeyError: 'curatedRank'
ERROR 2022-11-27T17:04:01 Exception id: 0xa1aa3
```

**Comment by waltflanagan53** [comment]
Seems to have resolved itself.
